<!doctype html>
<html class="theme-next pisces" lang="zh-Hans">
<head>
  <meta charset="UTF-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
<meta http-equiv="Cache-Control" content="no-transform">
<meta http-equiv="Cache-Control" content="no-siteapp">
  <link href="/lib/fancybox/source/jquery.fancybox.css?v=2.1.5" rel="stylesheet" type="text/css">
<link href="/lib/font-awesome/css/font-awesome.min.css?v=4.6.2" rel="stylesheet" type="text/css">
<link href="/css/main.css?v=5.1.1" rel="stylesheet" type="text/css">
  <meta name="keywords" content="C++ 异常 exception">
  <link rel="shortcut icon" type="image/x-icon" href="/images/favicon.ico?v=5.1.1">
<meta name="description" content="C++ 异常">
<meta name="keywords" content="cpp">
<meta property="og:type" content="article">
<meta property="og:title" content="C++ 异常">
<meta property="og:url" content="https://www.zfl9.com/cpp-exception.html">
<meta property="og:site_name" content="Otokaze's Blog">
<meta property="og:description" content="C++ 异常">
<meta property="og:image" content="https://www.zfl9.com/images/cpp-exception.jpg">
<meta property="og:updated_time" content="2019-02-18T12:42:42.281Z">
<meta name="twitter:card" content="summary">
<meta name="twitter:title" content="C++ 异常">
<meta name="twitter:description" content="C++ 异常">
<meta name="twitter:image" content="https://www.zfl9.com/images/cpp-exception.jpg">
<script type="text/javascript" id="hexo.configurations">
  var NexT = window.NexT || {};
  var CONFIG = {
    root: '/',
    scheme: 'Pisces',
    sidebar: {"position":"left","display":"post","offset":12,"offset_float":0,"b2t":false,"scrollpercent":false},
    fancybox: true,
    motion: false,
    duoshuo: {
      userId: '0',
      author: '博主'
    },
    algolia: {
      applicationID: '',
      apiKey: '',
      indexName: '',
      hits: {"per_page":10},
      labels: {"input_placeholder":"Search for Posts","hits_empty":"We didn't find any results for the search: ${query}","hits_stats":"${hits} results found in ${time} ms"}
    }
  };
</script>
  <link rel="canonical" href="https://www.zfl9.com/cpp-exception.html">
<link href="/js/prism/prism.css" rel="stylesheet">
  <title>C++ 异常 | Otokaze's Blog</title>
</head>
<body itemscope="" itemtype="http://schema.org/WebPage" lang="zh-Hans">
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
            (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
          m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');
  ga('create', 'UA-97872912-1', 'auto');
  ga('send', 'pageview');
</script>
  <script type="text/javascript">
    var _hmt = _hmt || [];
    (function() {
      var hm = document.createElement("script");
      hm.src = "https://hm.baidu.com/hm.js?3d58f51dbb2496a0e6d17b85065a5ae5";
      var s = document.getElementsByTagName("script")[0];
      s.parentNode.insertBefore(hm, s);
    })();
  </script>
  <div class="container sidebar-position-left page-post-detail ">
    <div class="headband"></div>
    <header id="header" class="header" itemscope="" itemtype="http://schema.org/WPHeader">
      <div class="header-inner"><div class="site-brand-wrapper">
  <div class="site-meta ">
    <div class="custom-logo-site-title">
      <a href="/" class="brand" rel="start">
        <span class="logo-line-before"><i></i></span>
        <span class="site-title">Otokaze's Blog</span>
        <span class="logo-line-after"><i></i></span>
      </a>
    </div>
        <h1 class="site-subtitle" itemprop="description">拼一年春夏秋冬，搏一生无怨无悔</h1>
  </div>
  <div class="site-nav-toggle">
    <button>
      <span class="btn-bar"></span>
      <span class="btn-bar"></span>
      <span class="btn-bar"></span>
    </button>
  </div>
</div>
<nav class="site-nav">
    <ul id="menu" class="menu">
        <li class="menu-item menu-item-home">
          <a href="/" rel="section">
              <i class="menu-item-icon fa fa-fw fa-home"></i> <br>
            首页
          </a>
        </li>
        <li class="menu-item menu-item-categories">
          <a href="/categories" rel="section">
              <i class="menu-item-icon fa fa-fw fa-th"></i> <br>
            分类
          </a>
        </li>
        <li class="menu-item menu-item-tags">
          <a href="/tags" rel="section">
              <i class="menu-item-icon fa fa-fw fa-tags"></i> <br>
            标签
          </a>
        </li>
        <li class="menu-item menu-item-archives">
          <a href="/archives" rel="section">
              <i class="menu-item-icon fa fa-fw fa-archive"></i> <br>
            归档
          </a>
        </li>
    </ul>
</nav>
 </div>
    </header>
    <main id="main" class="main">
      <div class="main-inner">
        <div class="content-wrap">
          <div id="content" class="content">
  <div id="posts" class="posts-expand">
  <article class="post post-type-normal " itemscope="" itemtype="http://schema.org/Article">
    <link itemprop="mainEntityOfPage" href="https://www.zfl9.com/cpp-exception.html">
    <span hidden itemprop="author" itemscope="" itemtype="http://schema.org/Person">
      <meta itemprop="name" content="Otokaze">
      <meta itemprop="description" content="">
      <meta itemprop="image" content="/images/avatar.jpg">
    </span>
    <span hidden itemprop="publisher" itemscope="" itemtype="http://schema.org/Organization">
      <meta itemprop="name" content="Otokaze's Blog">
    </span>
      <header class="post-header">
          <h2 class="post-title" itemprop="name headline">
                C++ 异常
          </h2>
        <div class="post-meta">
          <span class="post-time">
              <span class="post-meta-item-icon">
                <i class="fa fa-calendar-o"></i>
              </span>
                <span class="post-meta-item-text">发表于</span>
              <time title="创建于" itemprop="dateCreated datePublished" datetime="2017-08-29T07:51:00+08:00">
                2017-08-29
              </time>
          </span>
            <span class="post-category">
              <span class="post-meta-divider">|</span>
              <span class="post-meta-item-icon">
                <i class="fa fa-folder-o"></i>
              </span>
                <span class="post-meta-item-text">分类于</span>
                <span itemprop="about" itemscope="" itemtype="http://schema.org/Thing">
                  <a href="/categories/cpp/" itemprop="url" rel="index">
                    <span itemprop="name">cpp</span>
                  </a>
                </span>
            </span>
              <span class="post-comments-count">
                <span class="post-meta-divider">|</span>
                <span class="post-meta-item-icon">
                  <i class="fa fa-comment-o"></i>
                </span>
                <a href="/cpp-exception.html#comments" itemprop="discussionUrl">
                  <span class="post-comments-count disqus-comment-count" data-disqus-identifier="cpp-exception.html" itemprop="commentCount"></span>
                </a>
              </span>
             <span id="/cpp-exception.html" class="leancloud_visitors" data-flag-title="C++ 异常">
               <span class="post-meta-divider">|</span>
               <span class="post-meta-item-icon">
                 <i class="fa fa-eye"></i>
               </span>
                 <span class="post-meta-item-text">阅读次数 </span>
                 <span class="leancloud-visitors-count"></span>
             </span>
        </div>
      </header>
    <div class="post-body" itemprop="articleBody">
        <p>C++ 异常</p>
<a id="more"></a>
<h2 id="异常处理入门（try和catch）"><a href="#异常处理入门（try和catch）" class="headerlink" title="异常处理入门（try和catch）"></a>异常处理入门（try和catch）</h2><p>程序的错误大致可以分为三种，分别是<code>语法错误</code>、<code>逻辑错误</code>和<code>运行时错误</code>：<br>1) 语法错误在编译和链接阶段就能发现，只有 100% 符合语法规则的代码才能生成可执行程序；<br>语法错误是最容易发现、最容易定位、最容易排除的错误，程序员最不需要担心的就是这种错误；</p>
<p>2) 逻辑错误是说我们编写的代码思路有问题，不能够达到最终的目标，这种错误可以通过调试来解决；</p>
<p>3) 运行时错误是指程序在运行期间发生的错误，例如除数为 0、内存分配失败、数组越界、文件不存在等；<br>C++ <code>异常（Exception）</code>机制就是为解决运行时错误而引入的；</p>
<p>运行时错误如果放任不管，系统就会执行默认的操作，<code>终止程序运行</code>，也就是我们常说的<code>程序崩溃（Crash）</code>；<br>C++ 提供了<code>异常（Exception）机制</code>，让我们能够捕获运行时错误，给程序一次“起死回生”的机会，或者至少告诉用户发生了什么再终止程序；</p>
<p>一个发生运行时错误的例子：</p>
<pre><code class="language-cpp line-numbers"><script type="text/plain">#include <iostream>
#include <string>

using namespace std;

int main() {
    string str = "www.zfl9.com";

    char c1 = str[20];  // 下标越界，c1为垃圾值
    cout << c1 << endl;

    char c2 = str.at(20);   // 下标越界，抛出异常std::out_of_range
    cout << c2 << endl;
    return 0;
}
</script></code></pre>
<pre><code class="language-cpp line-numbers"><script type="text/plain"># root @ arch in ~/work on git:master x [8:45:25] C:134
$ g++ a.cpp

# root @ arch in ~/work on git:master x [8:45:31]
$ ./a.out
þ
terminate called after throwing an instance of 'std::out_of_range'
  what():  basic_string::at: __n (which is 20) >= this->size() (which is 12)
[1]    12312 abort (core dumped)  ./a.out
</script></code></pre>
<p>at() 是 string 类的一个成员函数，它会根据下标来返回字符串的一个字符；<br>与 [] 不同，at() 会检查下标是否越界，如果越界就抛出一个异常；而 [] 不做检查，不管下标是多少都会照常访问；</p>
<p>上面的代码中，下标 20 显然超出了字符串 str 的长度；<br>由于第 9 行代码不会检查下标越界，虽然有逻辑错误，但是程序能够正常运行；<br>而第 12 行代码则不同，at() 函数检测到下标越界会抛出一个异常，这个异常可以由程序员处理，但是我们在代码中并没有处理，所以系统只能<strong>执行默认的操作</strong>，也即<strong>终止程序执行</strong>；</p>
<p><strong>捕获异常</strong><br>我们可以借助 C++ 异常机制来捕获上面的异常，避免程序崩溃；捕获异常的语法为：</p>
<pre><code class="language-cpp line-numbers"><script type="text/plain">try {
    // 可能抛出异常的语句
} catch(exceptionType variable) {
    // 处理异常的语句
}
</script></code></pre>
<p><code>try</code>和<code>catch</code>都是 C++ 中的关键字，后跟语句块，不能省略<code>{}</code>；<br>try 中包含可能会抛出异常的语句，一旦有异常抛出就会被后面的 catch 捕获；</p>
<p>从 try 的意思可以看出，它只是“检测”语句块有没有异常，如果没有发生异常，它就“检测”不到；<br>catch 是“抓住”的意思，用来捕获并处理 try 检测到的异常；如果 try 语句块没有检测到异常（没有异常抛出），那么就不会执行 catch 中的语句；</p>
<p>catch 关键字后面的<code>exceptionType variable</code>指明了当前 catch 可以处理的异常类型，以及具体的出错信息；<br>我们稍后再对异常类型展开讲解，当务之急是演示一下<code>try-catch</code>的用法，先让读者有一个整体上的认识；</p>
<p>修改上面的代码，加入捕获异常的语句：</p>
<pre><code class="language-cpp line-numbers"><script type="text/plain">#include <iostream>
#include <string>
#include <exception>

using namespace std;

int main() {
    string str = "www.zfl9.com";

    try {
        char c1 = str[20];  // 下标越界，c1为垃圾值
        cout << c1 << endl;
    } catch(exception &e) {
        cout << e.what() << endl;
    }

    try {
        char c2 = str.at(20);   // 下标越界，抛出异常std::out_of_range
        cout << c2 << endl;
    } catch(exception &e) {
        cout << e.what() << endl;
    }

    return 0;
}
</script></code></pre>
<pre><code class="language-cpp line-numbers"><script type="text/plain"># root @ arch in ~/work on git:master x [8:59:32]
$ g++ a.cpp

# root @ arch in ~/work on git:master x [8:59:42]
$ ./a.out

basic_string::at: __n (which is 20) >= this->size() (which is 12)
</script></code></pre>
<p>可以看出，第一个 try 没有捕获到异常，输出了一个没有意义的字符（垃圾值）；<br>因为 [] 不会检查下标越界，不会抛出异常，所以即使有错误，try 也检测不到；<br>换句话说，<strong>发生异常时必须将异常明确地抛出，try 才能检测到；如果不抛出来，即使有异常 try 也检测不到</strong>；<br>所谓抛出异常，就是明确地告诉程序发生了什么错误；</p>
<p>第二个 try 检测到了异常，并交给 catch 处理，执行 catch 中的语句；<br>需要说明的是，异常一旦抛出，会立刻被 try 检测到，并且不会再执行异常点（异常发生位置）后面的语句；<br>本例中抛出异常的位置是第 18 行的 at() 函数，它后面的 cout 语句就不会再被执行，所以看不到它的输出；</p>
<p>说得直接一点，检测到异常后程序的执行流会发生跳转，从异常点跳转到 catch 所在的位置，位于异常点之后的、并且在当前 try 块内的语句就都不会再执行了；<br>即使 catch 语句成功地处理了错误，程序的执行流也不会再回退到异常点，所以这些语句永远都没有执行的机会了；本例中，第 19 行代码就是被跳过的代码；</p>
<p>执行完 catch 块所包含的代码后，程序会继续执行 catch 块后面的代码，就恢复了正常的执行流；</p>
<p>为了演示「不明确地抛出异常就检测不到异常」，大家不妨将第 11 行代码改为<code>char c1 = str[100000000];</code>；<br>访问第 20 个字符可能不会发生异常，但是访问第 1 亿个字符肯定会发生异常了，这个异常就是<strong>内存访问错误</strong>；<br>运行更改后的程序，会发现第 11 行代码产生了异常，导致程序崩溃了，这说明 try-catch 并没有捕获到这个异常；</p>
<p>关于「如何抛出异常」，我们将在下节讲解，这里重点是让大家明白异常的处理流程：<br><code>抛出（Throw）</code> –&gt; <code>检测（Try）</code> –&gt; <code>捕获（Catch）</code></p>
<p><strong>发生异常的位置</strong><br>异常可以发生在<code>当前的 try 块中</code>，也可以发生在<code>try 块所调用的某个函数中</code>，或者是<code>所调用的函数又调用了另外的一个函数，这个另外的函数中发生了异常</code>；这些异常，都可以被 try 检测到；</p>
<p>1) 下面的例子演示了 try 块中直接发生的异常：</p>
<pre><code class="language-cpp line-numbers"><script type="text/plain">#include <iostream>

using namespace std;

int main() {
    try {
        throw "Unknown Exception";
        cout << "after throw" << endl;
    } catch(const char * &e) {
        cout << e << endl;
    }

    return 0;
}
</script></code></pre>
<pre><code class="language-cpp line-numbers"><script type="text/plain"># root @ arch in ~/work on git:master x [9:11:26]
$ g++ a.cpp

# root @ arch in ~/work on git:master x [9:11:28]
$ ./a.out
Unknown Exception
</script></code></pre>
<p>2) 下面的例子演示了 try 块中调用的某个函数中发生了异常：</p>
<pre><code class="language-cpp line-numbers"><script type="text/plain">#include <iostream>

using namespace std;

void func() {
    throw "Unknown Exception (call func())";
    cout << "after throw" << endl;
}

int main() {
    try {
        func();
        cout << "after func()" << endl;
    } catch(const char * &e) {
        cout << e << endl;
    }

    return 0;
}
</script></code></pre>
<pre><code class="language-cpp line-numbers"><script type="text/plain"># root @ arch in ~/work on git:master x [9:14:42]
$ g++ a.cpp

# root @ arch in ~/work on git:master x [9:14:51]
$ ./a.out
Unknown Exception (call func())
</script></code></pre>
<p>3) try 块中调用了某个函数，该函数又调用了另外的一个函数，这个另外的函数抛出了异常：</p>
<pre><code class="language-cpp line-numbers"><script type="text/plain">#include <iostream>

using namespace std;

void func_inner() {
    throw "Unknown Exception (call func_inner())";
    cout << "func_inner()" << endl;
}

void func_outer() {
    func_inner();
    cout << "func_outer()" << endl;
}

int main() {
    try {
        func_outer();
        cout << "after func_outer()" << endl;
    } catch(const char * &e) {
        cout << e << endl;
    }

    return 0;
}
</script></code></pre>
<pre><code class="language-cpp line-numbers"><script type="text/plain"># root @ arch in ~/work on git:master x [9:17:44]
$ g++ a.cpp

# root @ arch in ~/work on git:master x [9:17:45]
$ ./a.out
Unknown Exception (call func_inner())
</script></code></pre>
<h2 id="异常类型以及多级catch"><a href="#异常类型以及多级catch" class="headerlink" title="异常类型以及多级catch"></a>异常类型以及多级catch</h2><p>首先来回顾一下上节讲到的 try-catch 的用法：</p>
<pre><code class="language-cpp line-numbers"><script type="text/plain">try {
    // 可能抛出异常的语句
} catch(exceptionType variable) {
    // 处理异常的语句
}
</script></code></pre>
<p>我们还遗留下一个问题，就是 catch 关键字后边的<code>exceptionType variable</code>，这节就来详细分析一下：</p>
<p>exceptionType 是异常类型，它指明了当前的 catch 可以处理什么类型的异常；<br>variable 是一个变量，用来接收异常信息；当程序抛出异常时，会创建一份数据，这份数据包含了错误信息，程序员可以根据这些信息来判断到底出了什么问题，接下来怎么处理；</p>
<p>异常既然是一份数据，那么就应该有数据类型；<br>C++ 规定，异常类型可以是 int、char、float、bool 等基本类型，也可以是指针、数组、字符串、结构体、类等聚合类型；<br>C++ 语言本身以及标准库中的函数抛出的异常，都是<code>exception</code>类或其子类的异常；也就是说，抛出异常时，会创建一个 exception 类或其子类的对象；</p>
<p><code>exceptionType variable</code>和<code>函数的形参</code>非常类似，当异常发生后，会将异常数据传递给 variable 这个变量，这和函数传参的过程类似；<br>当然，只有跟 exceptionType 类型匹配的异常数据才会被传递给 variable，否则 catch 不会接收这份异常数据，也不会执行 catch 块中的语句；换句话说，catch 不会处理当前的异常；</p>
<p><strong>我们可以将 catch 看做一个没有返回值的函数，当异常发生后 catch 会被调用，并且会接收实参（异常数据）</strong></p>
<p>但是 catch 和真正的函数调用又有区别：<br>1) 真正的函数调用，形参和实参的类型必须要匹配，或者可以自动转换，否则在编译阶段就报错了；<br>2) 而对于 catch，异常是在运行阶段产生的，它可以是任何类型，没法提前预测，所以不能在编译阶段判断类型是否正确，只能等到程序运行后，真的抛出异常了，再将异常类型和 catch 能处理的类型进行匹配，匹配成功的话就“调用”当前的 catch，否则就忽略当前的 catch；</p>
<p>总起来说，catch 和真正的函数调用相比，多了一个「在运行阶段将实参和形参匹配」的过程；</p>
<p>另外需要注意的是，如果不希望 catch 处理异常数据，也可以将 variable 省略掉，也即写作：</p>
<pre><code class="language-cpp line-numbers"><script type="text/plain">try {
    // 可能抛出异常的语句
} catch(exceptionType) {
    // 处理异常的语句
}
</script></code></pre>
<p>这样只会将异常类型和 catch 所能处理的类型进行匹配，不会传递异常数据了；</p>
<p>如果想匹配任何类型的异常，那么可以这样写：</p>
<pre><code class="language-cpp line-numbers"><script type="text/plain">try {
    // 可能抛出异常的语句
} catch (...) {
    // 处理异常的语句
}
</script></code></pre>
<p><strong>多级 catch</strong><br>前面的例子中，一个 try 对应一个 catch，这只是最简单的形式；其实，一个 try 后面可以跟多个 catch：</p>
<pre><code class="language-cpp line-numbers"><script type="text/plain">try {
    // 可能抛出异常的语句
} catch(exception_type_1 e) {
    // 处理异常的语句
} catch(exception_type_2 e) {
    // 处理异常的语句
}
</script></code></pre>
<p>当异常发生时，程序会按照<strong>从上到下</strong>的顺序，将异常类型和 catch 所能接收的类型逐个匹配；<br>一旦找到类型匹配的 catch 就停止检索，并将异常交给当前的 catch 处理（其他的 catch 不会被执行）；<br>如果最终也没有找到匹配的 catch，就只能交给系统处理，终止程序的运行；</p>
<p>下面的例子演示了多级 catch 的使用：</p>
<pre><code class="language-cpp line-numbers"><script type="text/plain">#include <iostream>

using namespace std;

class Base {};
class Derived : public Base {};

int main() {
    try {
        throw Derived();    // 创建一个 Derived 匿名对象，并抛出
    } catch (int) {
        cout << "Exception Type: int" << endl;
    } catch (char *) {
        cout << "Exception Type: char *" << endl;
    } catch (Base) {    // 向上转型，匹配成功
        cout << "Exception Type: class Base" << endl;
    } catch (Derived) {
        cout << "Exception Type: class Derived" << endl;
    }
    return 0;
}
</script></code></pre>
<pre><code class="language-cpp line-numbers"><script type="text/plain"># root @ arch in ~/work on git:master x [9:46:34]
$ g++ a.cpp
a.cpp: In function ‘int main()’:
a.cpp:17:7: warning: exception of type ‘Derived’ will be caught
     } catch (Derived) {
       ^~~~~
a.cpp:15:7: warning:    by earlier handler for ‘Base’
     } catch (Base) {    // 向上转型，匹配成功
       ^~~~~

# root @ arch in ~/work on git:master x [9:46:36]
$ ./a.out
Exception Type: class Base
</script></code></pre>
<p><strong>catch 在匹配过程中的类型转换</strong><br>C/C++ 中存在多种多样的类型转换，以<code>普通函数（非模板函数）</code>为例，发生函数调用时，如果实参和形参的类型不是严格匹配，那么会将实参的类型进行适当的转换，以适应形参的类型，这些转换包括：</p>
<ul>
<li>算数转换：例如 int 转换为 float，char 转换为 int，double 转换为 int 等；</li>
<li>向上转型：也就是派生类向基类的转换；</li>
<li>const 转换：也即将非 const 类型转换为 const 类型；</li>
<li>数组或函数指针转换：如果函数形参不是引用类型，那么数组名会转换为数组指针，函数名也会转换为函数指针；</li>
<li>用户自定的类型转换；</li>
</ul>
<p>catch 在匹配异常类型的过程中，也会进行类型转换，但是这种转换受到了更多的限制，仅能进行「<code>向上转型</code>」、「<code>const 转换</code>」和「<code>数组或函数指针转换</code>」，其他的都不能应用于 catch；</p>
<p><code>向上转型</code>在上面的例子中已经发生了，下面的例子演示了<code>const 转换</code>以及<code>数组和指针</code>的转换：</p>
<pre><code class="language-cpp line-numbers"><script type="text/plain">#include <iostream>

using namespace std;

int main() {
    try {
        int arr[] = {1, 2, 3, 4, 5};
        throw arr;
    } catch (const int *) {
        cout << "Exception Type: const int *" << endl;
    }
    return 0;
}
</script></code></pre>
<pre><code class="language-cpp line-numbers"><script type="text/plain"># root @ arch in ~/work on git:master x [9:52:18]
$ g++ a.cpp

# root @ arch in ~/work on git:master x [9:52:20]
$ ./a.out
Exception Type: const int *
</script></code></pre>
<p>arr 的类型为<code>int [5]</code>，由于没有匹配的类型，所以先转换为<code>int *</code>，还是没有匹配的，最后降为<code>const int *</code>，匹配成功</p>
<h2 id="throw关键字（抛出异常-异常规范）"><a href="#throw关键字（抛出异常-异常规范）" class="headerlink" title="throw关键字（抛出异常+异常规范）"></a>throw关键字（抛出异常+异常规范）</h2><p>C++ 异常处理的流程，具体为：<code>抛出（Throw）</code> –&gt; <code>检测（Try）</code> –&gt; <code>捕获（Catch）</code><br><strong>异常必须显式地抛出，才能被检测和捕获到；如果没有显式的抛出，即使有异常也检测不到</strong></p>
<p>在 C++ 中，我们使用 throw 关键字来显式地抛出异常，它的用法为：<code>throw exceptionData;</code><br><code>exceptionData</code>是异常数据，它可以包含任意的信息，完全有程序员决定；<br><code>exceptionData</code>可以是 int、float、bool 等基本类型，也可以是指针、数组、字符串、结构体、类等聚合类型；</p>
<p><strong>向上层抛出异常数据</strong><br>如果当前<code>catch</code>捕获到了异常，但是并不想处理，可以将其继续往外层抛出，被外层的<code>catch</code>再次捕获，让他们处理：</p>
<pre><code class="language-cpp line-numbers"><script type="text/plain">#include <iostream>

using namespace std;

void func() {
    try {
        throw "exception data";
    } catch (...) {
        throw;  // 不作处理，直接往上层抛出
    }
}

int main() {
    try {
        func();
    } catch (const char * &e) {
        cout << e << endl;
    }
}
</script></code></pre>
<pre><code class="language-cpp line-numbers"><script type="text/plain"># root @ arch in ~/work on git:master x [13:33:14]
$ g++ a.cpp

# root @ arch in ~/work on git:master x [13:33:38]
$ ./a.out
exception data
</script></code></pre>
<p><strong>throw 用作异常规范</strong></p>
<blockquote>
<p>异常规范是 C++98 新增的一项功能，但是后来的 C++11 已经将它抛弃了，不再建议使用；</p>
</blockquote>
<p>throw 关键字除了可以用在函数体中抛出异常，还可以用在函数头和函数体之间，指明当前函数能够抛出的异常类型，这称为<code>异常规范（Exception specification）</code>，有些教程也称为<code>异常指示符</code>或<code>异常列表</code>；</p>
<p>请看下面的例子：<br><code>double func(char param) throw(int);</code><br>这条语句声明了一个名为 func 的函数，它的返回值类型为 double，有一个 char 类型的参数，并且只能抛出 int 类型的异常；如果抛出其他类型的异常，try 将无法捕获，只能终止程序；</p>
<p>如果函数会抛出多种类型的异常，那么可以用逗号隔开：<br><code>double func(char param) throw(int, char, exception);</code></p>
<p>如果函数不会抛出任何异常，那么<code>()</code>中什么也不写：<br><code>double func(char param) throw();</code><br>如此，func() 函数就不能抛出任何类型的异常了，即使抛出了，try 也检测不到；</p>
<p><strong>请抛弃异常规范，不要再使用它</strong><br>异常规范的初衷是好的，它希望让程序员看到函数的定义或声明后，立马就知道该函数会抛出什么类型的异常，这样程序员就可以使用 try-catch 来捕获了；如果没有异常规范，程序员必须阅读函数源码才能知道函数会抛出什么异常；</p>
<p>不过这有时候也不容易做到：<br>例如，func_outer() 函数可能不会引发异常，但它调用了另外一个函数 func_inner()，这个函数可能会引发异常；<br>再如，您编写的函数调用了老式的库函数，此时不会引发异常，但是库更新以后这个函数却引发了异常；<br>总之，异常规范的初衷实现起来有点困难，所以大家达成的一致意见是，最好不要使用异常规范；</p>
<h2 id="exception类"><a href="#exception类" class="headerlink" title="exception类"></a>exception类</h2><p>C++语言本身或者标准库抛出的异常都是<code>exception</code>的子类，称为<code>标准异常（Standard Exception）</code>；你可以通过下面的语句来捕获所有的标准异常：</p>
<pre><code class="language-cpp line-numbers"><script type="text/plain">try {
    // 可能抛出异常的语句
} catch (exception &e) {
    // 处理异常的语句
}
</script></code></pre>
<p>之所以使用引用，是为了提高效率；如果不使用引用，就要经历一次对象拷贝（要调用拷贝构造函数）的过程；</p>
<p>exception 类位于<code>&lt;exception&gt;</code>头文件中，它被声明为：</p>
<pre><code class="language-cpp line-numbers"><script type="text/plain">class exception {
public:
    exception() throw();  // 构造函数
    exception(const exception &) throw();  // 拷贝构造函数
    exception & operator=(const exception &) throw();  // 运算符重载
    virtual ~exception() throw();  // 虚析构函数
    virtual const char * what() const throw();  // 虚函数
}
</script></code></pre>
<p>这里需要说明的是<code>what()</code>函数；<br>what() 函数返回一个能识别异常的字符串，正如它的名字“what”一样，可以粗略地告诉你这是什么异常；<br>不过C++标准并没有规定这个字符串的格式，各个编译器的实现也不同，所以 what() 的返回值仅供参考；</p>
<p><strong>exception 类的继承层次</strong><br><img src="/images/cpp-exception.jpg" alt="exception 继承层次"></p>
<p><strong>exception 类的直接派生类</strong>：</p>
<table>
<thead>
<tr>
<th style="text-align:center">异常名称</th>
<th style="text-align:center">说  明</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:center">logic_error</td>
<td style="text-align:center">逻辑错误</td>
</tr>
<tr>
<td style="text-align:center">runtime_error</td>
<td style="text-align:center">运行时错误</td>
</tr>
<tr>
<td style="text-align:center">bad_alloc</td>
<td style="text-align:center">使用 new 或 new[] 分配内存失败时抛出的异常</td>
</tr>
<tr>
<td style="text-align:center">bad_typeid</td>
<td style="text-align:center">使用 typeid 操作一个 NULL 指针，而且该指针是带有虚函数的类，这时抛出 bad_typeid 异常</td>
</tr>
<tr>
<td style="text-align:center">bad_cast</td>
<td style="text-align:center">使用 dynamic_cast 转换失败时抛出的异常</td>
</tr>
<tr>
<td style="text-align:center">ios_base::failure</td>
<td style="text-align:center">I/O 过程中出现的异常</td>
</tr>
<tr>
<td style="text-align:center">bad_exception</td>
<td style="text-align:center">这是个特殊的异常，如果函数的异常列表里声明了 bad_exception 异常，当函数内部抛出了异常列表中没有的异常时，如果调用的 unexpected() 函数中抛出了异常，不论什么类型，都会被替换为 bad_exception 类型</td>
</tr>
</tbody>
</table>
<p><strong>logic_error 的派生类</strong>：</p>
<table>
<thead>
<tr>
<th style="text-align:center">异常名称</th>
<th style="text-align:center">说  明</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:center">length_error</td>
<td style="text-align:center">试图生成一个超出该类型最大长度的对象时抛出该异常，例如 vector 的 resize 操作</td>
</tr>
<tr>
<td style="text-align:center">domain_error</td>
<td style="text-align:center">参数的值域错误，主要用在数学函数中，例如使用一个负值调用只能操作非负数的函数</td>
</tr>
<tr>
<td style="text-align:center">out_of_range</td>
<td style="text-align:center">超出有效范围</td>
</tr>
<tr>
<td style="text-align:center">invalid_argument</td>
<td style="text-align:center">参数不合适；在标准库中，当利用 string 对象构造 bitset 时，而 string 中的字符不是 0 或 1 的时候，抛出该异常；</td>
</tr>
</tbody>
</table>
<p><strong>runtime_error 的派生类</strong>：</p>
<table>
<thead>
<tr>
<th style="text-align:center">异常名称</th>
<th style="text-align:center">说  明</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:center">range_error</td>
<td style="text-align:center">计算结果超出了有意义的值域范围</td>
</tr>
<tr>
<td style="text-align:center">overflow_error</td>
<td style="text-align:center">算术计算上溢</td>
</tr>
<tr>
<td style="text-align:center">underflow_error</td>
<td style="text-align:center">算术计算下溢</td>
</tr>
</tbody>
</table>
<h2 id="RAII和异常安全"><a href="#RAII和异常安全" class="headerlink" title="RAII和异常安全"></a>RAII和异常安全</h2><p><strong>RAII是什么</strong>？<br>RAII 是 Resource Acquisition Is Initialization 的简称，是 C++ 语言的一种管理资源、避免泄漏的惯用法；利用的就是 C++ 构造的对象最终会被销毁的原则；RAII 的做法是使用一个对象，在其构造时获取对应的资源，在对象生命期内控制对资源的访问，使之始终保持有效，最后在对象析构的时候，释放构造时获取的资源；</p>
<p><strong>为什么要使用RAII</strong>？<br>上面说到 RAII 是用来管理资源、避免资源泄漏的方法；那么资源是如何定义的？在计算机系统中，资源是数量有限且对系统正常运行具有一定作用的元素；比如：网络套接字、互斥锁、文件句柄和内存等等，它们属于系统资源；由于系统的资源是有限的，就好比自然界的石油，铁矿一样，不是取之不尽，用之不竭的，所以，我们在编程使用系统资源时，都必须遵循一个步骤：<br>1) 申请资源；<br>2) 使用资源；<br>3) 释放资源；</p>
<p>第一步和第二步缺一不可，因为资源必须要申请才能使用的，使用完成以后，必须要释放，如果不释放的话，就会造成资源泄漏；</p>
<p>一个最简单的例子：</p>
<pre><code class="language-cpp line-numbers"><script type="text/plain">#include <iostream>
using namespace std;

int main() {
    int *p = new int[10]; // 申请内存资源
    // TODO 使用内存资源
    delete[] p; // 释放内存资源
    p = nullptr;
    return 0;
}
</script></code></pre>
<p><strong>RAII的作用</strong><br>RAII 的主要作用是在不失代码简洁性的同时，可以很好地保证代码的异常安全性；</p>
<p>当一个函数需要通过多个局部变量来管理资源时，RAII 就显得非常好用；因为只有被构造成功(构造函数没有抛出异常)的对象才会在返回时调用析构函数，同时析构函数的调用顺序恰好是它们构造顺序的反序，这样既可以保证多个资源(对象)的正确释放，又能满足多个资源之间的依赖关系；</p>
<p>由于 RAII 可以极大地简化资源管理，并有效地保证程序的正确和代码的简洁，所以通常会强烈建议在 C++ 中使用它；</p>
<p><strong>RAII对比finally</strong><br>虽然 RAII 和 finally 都能保证资源管理时的异常安全，但相对来说，使用 RAII 的代码相对更加简洁；<br>正如比雅尼·斯特劳斯特鲁普所说，“在真实环境中，调用资源释放代码的次数远多于资源类型的个数，所以相对于使用用 finally 来说，使用 RAII 能减少代码量”</p>
<p><strong>构造函数、析构函数可以抛出异常吗</strong>？<br>构造函数：在必要的情况下，可以抛出异常，表示对象构造失败，这时候是不会调用析构函数的，因为构造的并不是一个完整的对象；<br>析构函数：一定不能抛出异常，即使会发生异常也要在析构函数内部把异常吞掉，否则在异常转递的<code>堆栈辗转开解（stack-unwinding）</code>的过程中，terminate 函数被调用，而 terminate 通常调用 abort() 结束程序！</p>
<p>总结起来说：<br>如果在构造函数中申请了系统资源，那么在析构函数中需要有相应的资源释放操作，并且析构函数不能抛出任何异常！<br>对于动态分配的内存，请尽量不要直接使用 new/delete 操作符，尽量使用 C++11 中的智能指针来进行内存的申请和释放！</p>
<p><strong>异常安全</strong><br>异常安全的代码是指，满足两个条件：</p>
<ul>
<li>异常中立性<ul>
<li>指当你的代码（包括你调用的代码）引发异常时，这个异常能保持原样传递到外层调用代码；</li>
</ul>
</li>
<li>异常安全性<ul>
<li>抛出异常后，资源不泄露；</li>
<li>抛出异常后，不会使原有数据恶化（例如正常指针变野指针）；</li>
<li>少些 try catch，因为大量的 try catch 会影响代码逻辑；导致代码丑陋混乱不优雅；</li>
</ul>
</li>
</ul>
<p>一段代码要具有异常安全性，必须同时具有异常中立性和一定等级的异常安全性保证；</p>
<p>C++ 中”异常安全函数”提供了三种安全等级：<br>1) <code>基本承诺</code>：如果异常被抛出，对象内的任何成员仍然能保持有效状态，没有数据的破坏及资源泄漏；但对象的现实状态是不可估计的，即不一定是调用前的状态，但至少保证符合对象正常的要求；<br>2) <code>强烈保证</code>：如果异常被抛出，对象的状态保持不变；即如果调用成功，则完全成功；如果调用失败，则对象依然是调用前的状态；<br>3) <code>不抛异常保证</code>：函数承诺不会抛出任何异常；一般内置类型的所有操作都有不抛异常的保证；</p>
<p>如果一个函数不能提供上述保证之一，则不具备异常安全性；</p>
<p>最后，需要提醒的是：<br>1) 不要滥用异常，也不要摒弃异常，只有在必要的情况下去考虑 try…catch；<br>2) 千万不要使用 try…catch 进行程序的逻辑控制，不要拿它们当 if…else 用；<br>3) 为了让代码具有更好的异常安全性，首先是”用对象来管理资源“（RAII），以避免资源的泄漏；其次，在异常安全性等级上，应该尽可能地往更高的等级上来限制；<br>4) “在恰当的场合使用恰当的特性”对每个称职的 C++ 程序员来说都是一个基本标准；</p>
    </div>
    <div>
    </div>
    <div>
    </div>
    <div>
    </div>
    <footer class="post-footer">
        <div class="post-tags">
            <a href="/tags/cpp/" rel="tag"># cpp</a>
        </div>
        <div class="post-nav">
          <div class="post-nav-next post-nav-item">
              <a href="/cpp-oop.html" rel="next" title="C++ 面向对象进阶">
                <i class="fa fa-chevron-left"></i> C++ 面向对象进阶
              </a>
          </div>
          <span class="post-nav-divider"></span>
          <div class="post-nav-prev post-nav-item">
              <a href="/cpp-template.html" rel="prev" title="C++ 模板">
                C++ 模板 <i class="fa fa-chevron-right"></i>
              </a>
          </div>
        </div>
    </footer>
  </article>
    <div class="post-spread">
    </div>
  </div>
          </div>
  <div class="comments" id="comments">
      <div id="disqus_thread">
        <noscript>
          Please enable JavaScript to view the
          <a href="https://disqus.com/?ref_noscript" rel="external nofollow noopener noreferrer" target="_blank">comments powered by Disqus.</a>
        </noscript>
      </div>
  </div>
        </div>
  <div class="sidebar-toggle">
    <div class="sidebar-toggle-line-wrap">
      <span class="sidebar-toggle-line sidebar-toggle-line-first"></span>
      <span class="sidebar-toggle-line sidebar-toggle-line-middle"></span>
      <span class="sidebar-toggle-line sidebar-toggle-line-last"></span>
    </div>
  </div>
  <aside id="sidebar" class="sidebar">
    <div class="sidebar-inner">
        <ul class="sidebar-nav motion-element">
          <li class="sidebar-nav-toc sidebar-nav-active" data-target="post-toc-wrap">
            文章目录
          </li>
          <li class="sidebar-nav-overview" data-target="site-overview">
            站点概览
          </li>
        </ul>
      <section class="site-overview sidebar-panel">
        <div class="site-author motion-element" itemprop="author" itemscope="" itemtype="http://schema.org/Person">
          <img class="site-author-image" itemprop="image" src="/images/avatar.jpg" alt="Otokaze">
          <p class="site-author-name" itemprop="name">Otokaze</p>
              <p class="site-description motion-element" itemprop="description"></p>
        </div>
        <nav class="site-state motion-element">
            <div class="site-state-item site-state-posts">
              <a href="/archives">
                <span class="site-state-item-count">170</span>
                <span class="site-state-item-name">日志</span>
              </a>
            </div>
            <div class="site-state-item site-state-categories">
              <a href="/categories/index.html">
                <span class="site-state-item-count">43</span>
                <span class="site-state-item-name">分类</span>
              </a>
            </div>
            <div class="site-state-item site-state-tags">
              <a href="/tags/index.html">
                <span class="site-state-item-count">46</span>
                <span class="site-state-item-name">标签</span>
              </a>
            </div>
        </nav>
        <div class="links-of-author motion-element">
              <span class="links-of-author-item">
                <a href="https://github.com/zfl9" target="_blank" title="GitHub rel=" external="" nofollow""="" rel="external nofollow noopener noreferrer">
                    <i class="fa fa-fw fa-github"></i>
                  GitHub
                </a>
              </span>
              <span class="links-of-author-item">
                <a href="mailto:zfl9.com@gmail.com" target="_blank" title="Email rel=" external="" nofollow""="" rel="external nofollow noopener noreferrer">
                    <i class="fa fa-fw fa-envelope"></i>
                  Email
                </a>
              </span>
              <span class="links-of-author-item">
                <a href="https://gitlab.com/zfl9" target="_blank" title="GitLab rel=" external="" nofollow""="" rel="external nofollow noopener noreferrer">
                    <i class="fa fa-fw fa-gitlab"></i>
                  GitLab
                </a>
              </span>
              <span class="links-of-author-item">
                <a href="https://t.me/Otokaze" target="_blank" title="Telegram rel=" external="" nofollow""="" rel="external nofollow noopener noreferrer">
                    <i class="fa fa-fw fa-telegram"></i>
                  Telegram
                </a>
              </span>
        </div>
      </section>
      <!--noindex-->
        <section class="post-toc-wrap motion-element sidebar-panel sidebar-panel-active">
          <div class="post-toc">
              <div class="post-toc-content"><ol class="nav"><li class="nav-item nav-level-2"><a class="nav-link" href="#异常处理入门（try和catch）"><span class="nav-number">1.</span> <span class="nav-text">异常处理入门（try和catch）</span></a></li><li class="nav-item nav-level-2"><a class="nav-link" href="#异常类型以及多级catch"><span class="nav-number">2.</span> <span class="nav-text">异常类型以及多级catch</span></a></li><li class="nav-item nav-level-2"><a class="nav-link" href="#throw关键字（抛出异常-异常规范）"><span class="nav-number">3.</span> <span class="nav-text">throw关键字（抛出异常+异常规范）</span></a></li><li class="nav-item nav-level-2"><a class="nav-link" href="#exception类"><span class="nav-number">4.</span> <span class="nav-text">exception类</span></a></li><li class="nav-item nav-level-2"><a class="nav-link" href="#RAII和异常安全"><span class="nav-number">5.</span> <span class="nav-text">RAII和异常安全</span></a></li></ol></div>
          </div>
        </section>
      <!--/noindex-->
    </div>
  </aside>
      </div>
    </main>
    <footer id="footer" class="footer">
      <div class="footer-inner">
        <div class="copyright">
  &copy;  2016 - 
  <span itemprop="copyrightYear">2020</span>
  <span class="with-love">
    <i class="fa fa-heart"></i>
  </span>
  <span class="author" itemprop="copyrightHolder">Otokaze</span>
</div>
<script src="/js/clipboard.min.js"></script>
<script src="/js/prism/prism.js" async></script>
      </div>
    </footer>
      <div class="back-to-top">
        <i class="fa fa-arrow-up"></i>
      </div>
  </div>
<script type="text/javascript">
  if (Object.prototype.toString.call(window.Promise) !== '[object Function]') {
    window.Promise = null;
  }
</script>
  <script type="text/javascript" src="/lib/jquery/index.js?v=2.1.3"></script>
  <script type="text/javascript" src="/lib/fastclick/lib/fastclick.min.js?v=1.0.6"></script>
  <script type="text/javascript" src="/lib/jquery_lazyload/jquery.lazyload.js?v=1.9.7"></script>
  <script type="text/javascript" src="/lib/velocity/velocity.min.js?v=1.2.1"></script>
  <script type="text/javascript" src="/lib/velocity/velocity.ui.min.js?v=1.2.1"></script>
  <script type="text/javascript" src="/lib/fancybox/source/jquery.fancybox.pack.js?v=2.1.5"></script>
  <script type="text/javascript" src="/js/src/utils.js?v=5.1.1"></script>
  <script type="text/javascript" src="/js/src/motion.js?v=5.1.1"></script>
  <script type="text/javascript" src="/js/src/affix.js?v=5.1.1"></script>
  <script type="text/javascript" src="/js/src/schemes/pisces.js?v=5.1.1"></script>
  <script type="text/javascript" src="/js/src/scrollspy.js?v=5.1.1"></script>
<script type="text/javascript" src="/js/src/post-details.js?v=5.1.1"></script>
  <script type="text/javascript" src="/js/src/bootstrap.js?v=5.1.1"></script>
      <script id="dsq-count-scr" src="https://otokaze.disqus.com/count.js" async></script>
      <script type="text/javascript">
        var disqus_config = function () {
          this.page.url = 'https://www.zfl9.com/cpp-exception.html';
          this.page.identifier = 'cpp-exception.html';
          this.page.title = 'C++ 异常';
        };
        var d = document, s = d.createElement('script');
        s.src = 'https://otokaze.disqus.com/embed.js';
        s.setAttribute('data-timestamp', '' + +new Date());
        (d.head || d.body).appendChild(s);
      </script>
  <script src="https://cdn1.lncld.net/static/js/av-core-mini-0.6.1.js"></script>
  <script>AV.initialize("3hhdw6gOg9wavsharVwVjqI3-gzGzoHsz", "O5WfDffqFsgmAVPwNY9of3QU");</script>
  <script>
    function showTime(Counter) {
      var query = new AV.Query(Counter);
      var entries = [];
      var $visitors = $(".leancloud_visitors");
      $visitors.each(function () {
        entries.push( $(this).attr("id").trim() );
      });
      query.containedIn('url', entries);
      query.find()
        .done(function (results) {
          var COUNT_CONTAINER_REF = '.leancloud-visitors-count';
          if (results.length === 0) {
            $visitors.find(COUNT_CONTAINER_REF).text(0);
            return;
          }
          for (var i = 0; i < results.length; i++) {
            var item = results[i];
            var url = item.get('url');
            var time = item.get('time');
            var element = document.getElementById(url);
            $(element).find(COUNT_CONTAINER_REF).text(time);
          }
          for(var i = 0; i < entries.length; i++) {
            var url = entries[i];
            var element = document.getElementById(url);
            var countSpan = $(element).find(COUNT_CONTAINER_REF);
            if( countSpan.text() == '') {
              countSpan.text(0);
            }
          }
        })
        .fail(function (object, error) {
          console.log("Error: " + error.code + " " + error.message);
        });
    }
    function addCount(Counter) {
      var $visitors = $(".leancloud_visitors");
      var url = $visitors.attr('id').trim();
      var title = $visitors.attr('data-flag-title').trim();
      var query = new AV.Query(Counter);
      query.equalTo("url", url);
      query.find({
        success: function(results) {
          if (results.length > 0) {
            var counter = results[0];
            counter.fetchWhenSave(true);
            counter.increment("time");
            counter.save(null, {
              success: function(counter) {
                var $element = $(document.getElementById(url));
                $element.find('.leancloud-visitors-count').text(counter.get('time'));
              },
              error: function(counter, error) {
                console.log('Failed to save Visitor num, with error message: ' + error.message);
              }
            });
          } else {
            var newcounter = new Counter();
            /* Set ACL */
            var acl = new AV.ACL();
            acl.setPublicReadAccess(true);
            acl.setPublicWriteAccess(true);
            newcounter.setACL(acl);
            /* End Set ACL */
            newcounter.set("title", title);
            newcounter.set("url", url);
            newcounter.set("time", 1);
            newcounter.save(null, {
              success: function(newcounter) {
                var $element = $(document.getElementById(url));
                $element.find('.leancloud-visitors-count').text(newcounter.get('time'));
              },
              error: function(newcounter, error) {
                console.log('Failed to create');
              }
            });
          }
        },
        error: function(error) {
          console.log('Error:' + error.code + " " + error.message);
        }
      });
    }
    $(function() {
      var Counter = AV.Object.extend("Counter");
      if ($('.leancloud_visitors').length == 1) {
        addCount(Counter);
      } else if ($('.post-title-link').length > 1) {
        showTime(Counter);
      }
    });
  </script>
<script>
(function(){
    var bp = document.createElement('script');
    var curProtocol = window.location.protocol.split(':')[0];
    if (curProtocol === 'https') {
        bp.src = 'https://zz.bdstatic.com/linksubmit/push.js';        
    }
    else {
        bp.src = 'http://push.zhanzhang.baidu.com/push.js';
    }
    var s = document.getElementsByTagName("script")[0];
    s.parentNode.insertBefore(bp, s);
})();
</script>
</body>
</html>
